In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Lendo tabela geral do ENEM 2024
caminho = '/content/drive/MyDrive/analise-diagnostico-enem2024/RESULTADOS_2024.csv'
df = pd.read_csv(caminho, sep = ';', encoding='latin-1')

## Tratando dados

In [ ]:
# Identificando colunas
df.columns

Index(['NU_SEQUENCIAL', 'NU_ANO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC',
       'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC',
       'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA',
       'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN',
       'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN',
       'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH',
       'NU_NOTA_LC', 'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH',
       'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN',
       'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT',
       'TP_STATUS_REDACAO', 'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3',
       'NU_NOTA_COMP4', 'NU_NOTA_COMP5', 'NU_NOTA_REDACAO'],
      dtype='object')

In [ ]:
# Atribuindo as colunas desejadas
df = df[['NU_SEQUENCIAL','NO_MUNICIPIO_PROVA', 'SG_UF_PROVA', 'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']]

In [ ]:
# Verificando se tem duplicatas
df.duplicated().sum()

np.int64(0)

In [ ]:
# Excluindo linhas com notas faltantes
df = df.dropna(subset=['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO'])

In [ ]:
# Resetando o índice
df = df.reset_index(drop=True)

In [ ]:
# Somando dados faltantes
df.isna().sum()

NU_SEQUENCIAL                   0
NO_MUNICIPIO_PROVA              0
SG_UF_PROVA                     0
TP_DEPENDENCIA_ADM_ESC    1796661
TP_LOCALIZACAO_ESC        1796661
NU_NOTA_CN                      0
NU_NOTA_CH                      0
NU_NOTA_LC                      0
NU_NOTA_MT                      0
NU_NOTA_REDACAO                 0
dtype: int64

In [ ]:
# Atualizando nome das colunas por nomes mais intuitivos
df = df.rename(columns={
  'NU_SEQUENCIAL':'numero_seq_aluno',
  'NO_MUNICIPIO_PROVA':'municipio',
  'SG_UF_PROVA':'uf',
  'TP_DEPENDENCIA_ADM_ESC':'dependencia',
  'TP_LOCALIZACAO_ESC':'localizacao',
  'NU_NOTA_CN':'nota_ciencias_naturais',
  'NU_NOTA_CH':'nota_ciencias_humanas',
  'NU_NOTA_LC':'nota_linguagens',
  'NU_NOTA_MT':'nota_matematica',
  'NU_NOTA_REDACAO':'nota_redacao'
  })

In [ ]:
# Verificando o tipo de dados das colunas para possível tratamento
df.dtypes

numero_seq_aluno            int64
municipio                  object
uf                         object
dependencia               float64
localizacao               float64
nota_ciencias_naturais    float64
nota_ciencias_humanas     float64
nota_linguagens           float64
nota_matematica           float64
nota_redacao              float64
dtype: object

In [ ]:
# Tratando dados objects nulos
df['dependencia'] = df['dependencia'].fillna('Não informado')
df['localizacao'] = df['localizacao'].fillna('Não informado')

In [ ]:
# Substituindo valores da coluna 'dependencia'
df['dependencia'] = df['dependencia'].replace({
    1:'Federal',
    2:'Estadual',
    3:'Municipal',
    4:'Privada'
})

In [ ]:
# Substituindo valores da coluna 'localizacao'
df['localizacao'] = df['localizacao'].replace({
    1:'Urbana',
    2:'Rural'
})

In [ ]:
# Verificação final
print(df.info())
print(df.describe(include='all'))
print('Duplicatas restantes:', df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2990093 entries, 0 to 2990092
Data columns (total 10 columns):
 #   Column                  Dtype
---  ------                  -----
 0   numero_seq_aluno        int64
 1   municipio               object
 2   uf                      object
 3   dependencia             object
 4   localizacao             object
 5   nota_ciencias_naturais  float64
 6   nota_ciencias_humanas   float64
 7   nota_linguagens         float64
 8   nota_matematica         float64
 9   nota_redacao            float64
dtypes: float64(5), int64(1), object(4)
memory usage: 228.1+ MB
None
        numero_seq_aluno  municipio       uf    dependencia    localizacao  \
count       2.990093e+06    2990093  2990093        2990093        2990093
unique               NaN       1717       27              5              3
top                  NaN  São Paulo       SP  Não informado  Não informado
freq                 NaN     121804   464414        1796661        1796661
mean        2.026695e+06        NaN      NaN            NaN            NaN
std         1.212741e+06        NaN      NaN            NaN            NaN
min         2.000000e+00        NaN      NaN            NaN            NaN
25%         9.710170e+05        NaN      NaN            NaN            NaN
50%         1.994373e+06        NaN      NaN            NaN            NaN
75%         3.039325e+06        NaN      NaN            NaN            NaN
max         4.332944e+06        NaN      NaN            NaN            NaN

        nota_ciencias_naturais  nota_ciencias_humanas  nota_linguagens  \
count             2.990093e+06           2.990093e+06     2.990093e+06
unique                     NaN                    NaN              NaN
top                        NaN                    NaN              NaN
freq                       NaN                    NaN              NaN
mean              4.940260e+02           5.142128e+02     5.266217e+02
std               7.898947e+01           9.155594e+01     6.865750e+01
min               0.000000e+00           0.000000e+00     0.000000e+00
25%               4.315000e+02           4.502000e+02     4.867000e+02
50%               4.885000e+02           5.194000e+02     5.334000e+02
75%               5.503000e+02           5.785000e+02     5.736000e+02
max               8.672000e+02           8.197000e+02     7.958000e+02

        nota_matematica  nota_redacao
count      2.990093e+06  2.990093e+06
unique              NaN           NaN
top                 NaN           NaN
freq                NaN           NaN
mean       5.270813e+02  6.346660e+02
std        1.141715e+02  2.090954e+02
min        0.000000e+00  0.000000e+00
25%        4.313000e+02  5.200000e+02
50%        4.992000e+02  6.400000e+02
75%        6.110000e+02  8.000000e+02
max        9.619000e+02  1.000000e+03
Duplicatas restantes: 0

In [ ]:
# Criando caminho de saída
caminho_saida_tabela = '/content/drive/MyDrive/analise-diagnostico-enem2024/tabela_enem2024.csv'

In [ ]:
df.to_csv(caminho_saida_tabela, index=False)